language: generic
dist: bionic

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-9
      env: CC='g++-9' CXX='g++-9'
notifications:
  email:
    on_success: never
  on_failure: never
