language: shell
python:
    - "3.6"


git:
  submodules: false
# Use sed to replace the SSH URL with the public URL, then initialize submodules
before_install:
  - sed -i 's/git@github.com:/https:\/\/github.com\//' ".gitmodules"
  - git submodule update --init --recursive

matrix:
  include:
        - compiler: clang
          os: linux
          dist: xenial
          addons:
            apt:
              sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-xenial-8']
              packages: ['g++-9', 'clang++-8', 'clang-tidy-8']
          env:
            - NAME=clang8
            - CXX=clang++-8
            - CLANG_TIDY=clang-tidy-8
          script:
            - make RELEASE=1
        - compiler: gcc
          os: linux
          dist: xenial
          addons:
            apt:
              sources: ['ubuntu-toolchain-r-test']
              packages: ['g++-9']
          env:
            - NAME=gcc
            - CXX=g++-9
          script:
            - make RELEASE=1
        - os: windows
          env:
            - MSBUILD_PATH="C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\Current\Bin"
            - PYTHON_PATH="C:/Python37:C:/Python37/Scripts:/c/Python37:/c/Python37/Scripts"
            #:/c/Python37/Scripts:$PATH
          install:
            - choco install python --version=3.7.2
            - choco install visualstudio2019buildtools --package-parameters "--add Microsoft.VisualStudio.Component.VC.Tools.x86.x64"
#            - choco install dotnetcore-sdk
#            - dotnet restore
          script:
            - export PATH=$PYTHON_PATH:$MSBUILD_PATH:$PATH
            - ./buildwindows.bat
    
notifications:
  email: false
  
before_deploy:
      # Set up git user name and tag this commit
      #- git config --local user.name "YOUR GIT USER NAME"
      #- git config --local user.email "YOUR GIT USER EMAIL"
      #- export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)}
      #- git tag $TRAVIS_TAG
      if [ "$TRAVIS_OS_NAME" == "windows" ]; then 
        copy "./x64/JSONBuild/CPPRPJSON.exe" "cpprpjson-$NAME-$TRAVIS_TAG.exe"; 
        copy "./x64/JSONBuild/CPPRP.lib" "cpprp-$NAME-$TRAVIS_TAG.lib"; 
      fi
      
      if [ "$TRAVIS_OS_NAME" != "windows" ]; then mv "./build/test" "cpprp-$NAME-$TRAVIS_TAG"; fi

deploy:
  - provider: releases
    api_key: 
      secure: "2URYSVXtASX+UxairK0KwzxtagEBHxO3ghdwPnuOUonjx3oe0m3BHk6F171rulO7FOrujVqQ8rw8ruNnPHTNv76UeIK8nru3JU0v0q0dWDGFdUJZvgMsl9DLJkLUMiPsqnghfBXQTH1J399xf8ABd9/1r3/80PPBA8xCGQlF4Bl5sA6wJRPrIUGOayambI4pAeeO9f6evtoqM+pU2bq1VXrjZcILk6Rf9CLmvrQZaqwALhoTndmmzeS0hKBX6ts3v9kA5EkcNfqTDaR+mS8jr/pUIcwYniic45oNNRuCuifryVDuMbudvKnpw1XyrzbD92pH1W/hSD7hX5sjFuEP717G8DMSjoV3YdEAjUOZsN0le/L3GRBhAwqweOewcUdGRPgX0IjtWmppSPHwHLDtkGLG8W6PQBOifjp9mXAS05Uj7SiQYVQSz9vN0rl/kKl4J7TMG6pgDmlujP4lTmOjnUIFGb8iyY13c+FEa4HO+BDcHyHQX0ynIPpNosnUrW7ZPJuGn3hXMQCn8p8T0WE4Om+4C5g2tc+GpSWtY/VrAz41bTUll9siFv/t6xqf8F7HjQhwcsy6iUeN8DxAuzMhfgsphibuFLIuuymn9Tds6d/ai5e5fVctw4UQlOe4muwELUL9yTF8Crx4WpZLp6aAHHsMKHOgQ4ysx96timEV8eY="
    file: "cpprp-$NAME-$TRAVIS_TAG"
    skip_cleanup: true
    draft: true
    on:
      os: linux
      tags: true
      branch: master
  - provider: releases
    api_key: 
      secure: "2URYSVXtASX+UxairK0KwzxtagEBHxO3ghdwPnuOUonjx3oe0m3BHk6F171rulO7FOrujVqQ8rw8ruNnPHTNv76UeIK8nru3JU0v0q0dWDGFdUJZvgMsl9DLJkLUMiPsqnghfBXQTH1J399xf8ABd9/1r3/80PPBA8xCGQlF4Bl5sA6wJRPrIUGOayambI4pAeeO9f6evtoqM+pU2bq1VXrjZcILk6Rf9CLmvrQZaqwALhoTndmmzeS0hKBX6ts3v9kA5EkcNfqTDaR+mS8jr/pUIcwYniic45oNNRuCuifryVDuMbudvKnpw1XyrzbD92pH1W/hSD7hX5sjFuEP717G8DMSjoV3YdEAjUOZsN0le/L3GRBhAwqweOewcUdGRPgX0IjtWmppSPHwHLDtkGLG8W6PQBOifjp9mXAS05Uj7SiQYVQSz9vN0rl/kKl4J7TMG6pgDmlujP4lTmOjnUIFGb8iyY13c+FEa4HO+BDcHyHQX0ynIPpNosnUrW7ZPJuGn3hXMQCn8p8T0WE4Om+4C5g2tc+GpSWtY/VrAz41bTUll9siFv/t6xqf8F7HjQhwcsy6iUeN8DxAuzMhfgsphibuFLIuuymn9Tds6d/ai5e5fVctw4UQlOe4muwELUL9yTF8Crx4WpZLp6aAHHsMKHOgQ4ysx96timEV8eY="
    file:
      - "cpprp-$NAME-$TRAVIS_TAG.lib"
      - "cpprpjson-$NAME-$TRAVIS_TAG.exe"
    skip_cleanup: true
    draft: true
    on:
      os: linux
      tags: true
      branch: master      
      
      
branches:
  only:
    - master
    - /^\d+\.\d+\.\d+.*$/ #https://travis-ci.community/t/pushing-tag-does-not-trigger-deployment-to-github-releases/3098
